# version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rag_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rag_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - rag_network
    command: mongod --noauth

  mongo-express:
    image: mongo-express:1.0.0
    container_name: rag_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - rag_network

  rag-api:
    build: .
    container_name: rag_api_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/rag_db
      MONGODB_DATABASE: rag_db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - rag_network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  rag_network:
    driver: bridge