# docker-compose.yml
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on: [db]
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports: ["9000:9000"]
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:5.0
    container_name: sonar_scanner
    profiles: ["tools"]
    command: ["sleep", "infinity"]
    volumes:
      - ./source_bug:/usr/src
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
    depends_on:
      - sonarqube
    networks:
      - default

  bearer:
    platform: linux/amd64
    image: bearer/bearer:latest-amd64
    container_name: bearer_scanner
    profiles: ["tools"]
    command: ["sleep", "infinity"]
    networks:
      - default
  
  db:
    image: postgres:15
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  pg_data:
